# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20170718_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='This dojo was prexisting'),
            preserve_default=False,
        ),
    ]
